/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ControleDeBrassagem.Interface;

import org.json.simple.JSONArray;

/**
 *
 * @author Gazebo
 */
public class TelaNovaBrassagem extends javax.swing.JFrame {
    int targetValue;
    int target1Value;
    int config;
    int rampsNumber;
    int actualRamp;
    int hopsNumber;
    int actualHop;
    StatusController status;
    JSONArray  allHopsArray;
    JSONArray allRampsArray;
    JSONArray actualRampArray;
    
    /**
     * Creates new form TelaNovaBrassagem
     */
    public TelaNovaBrassagem() {
        this.setExtendedState(Interface.MAXIMIZED_BOTH); 
        this.setUndecorated(true);
        initComponents();
        config = 0;
        actualRamp = 1;
        actualHop = 1;
        targetValue = 0;
        target1Value = 0;
        lblTarget.setText("0");
        lblTarget1.setText("0");
        allRampsArray  = new JSONArray();
        allHopsArray  = new JSONArray();
       
        setSecondConfigVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblTarget = new javax.swing.JLabel();
        lblNext = new javax.swing.JLabel();
        iconTopArrow1 = new javax.swing.JLabel();
        iconTopArrow = new javax.swing.JLabel();
        btnTopArrow = new javax.swing.JButton();
        iconBottomArrow1 = new javax.swing.JLabel();
        iconBottomArrow = new javax.swing.JLabel();
        btnBottomArrow = new javax.swing.JButton();
        lblConfig = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        lblConfig1 = new javax.swing.JLabel();
        lblTarget1 = new javax.swing.JLabel();
        lblUnidTarget1 = new javax.swing.JLabel();
        iconTargetBkg1 = new javax.swing.JLabel();
        lblUnidTarget = new javax.swing.JLabel();
        iconTargetBkg = new javax.swing.JLabel();
        btnBottomArrow1 = new javax.swing.JButton();
        btnTopArrow1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 40)); // NOI18N
        jLabel2.setText("NOVA BRASSAGEM");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, -1));

        lblTarget.setFont(new java.awt.Font("Comic Sans MS", 1, 30)); // NOI18N
        lblTarget.setText("39");
        getContentPane().add(lblTarget, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 60, 80));

        lblNext.setFont(new java.awt.Font("Comic Sans MS", 1, 22)); // NOI18N
        lblNext.setText("PRÓXIMO");
        getContentPane().add(lblNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 520, 180, 50));

        iconTopArrow1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ControleDeBrassagem/Images/Polygon 1.png"))); // NOI18N
        getContentPane().add(iconTopArrow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 350, 100, 60));

        iconTopArrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ControleDeBrassagem/Images/Polygon 1.png"))); // NOI18N
        getContentPane().add(iconTopArrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 180, 100, 60));

        btnTopArrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTopArrowActionPerformed(evt);
            }
        });
        getContentPane().add(btnTopArrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 200, 40, 30));

        iconBottomArrow1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ControleDeBrassagem/Images/Polygon 5.png"))); // NOI18N
        getContentPane().add(iconBottomArrow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 410, 100, 70));

        iconBottomArrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ControleDeBrassagem/Images/Polygon 5.png"))); // NOI18N
        getContentPane().add(iconBottomArrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 240, 100, 70));

        btnBottomArrow.setBackground(new java.awt.Color(51, 153, 255));
        btnBottomArrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBottomArrowActionPerformed(evt);
            }
        });
        getContentPane().add(btnBottomArrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 250, 40, 30));

        lblConfig.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        lblConfig.setText("Temperatura inicial panela 1:");
        getContentPane().add(lblConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 600, 50));

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 21)); // NOI18N
        jLabel11.setText("CANCELAR");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 590, 180, 50));

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ControleDeBrassagem/Images/Rectangle 11.png"))); // NOI18N
        btnCancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 590, 140, 50));

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ControleDeBrassagem/Images/Rectangle 11.png"))); // NOI18N
        btnNext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 520, 140, 50));

        lblConfig1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        lblConfig1.setText("Temperatura inicial panela 1:");
        getContentPane().add(lblConfig1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 600, 50));

        lblTarget1.setFont(new java.awt.Font("Comic Sans MS", 1, 30)); // NOI18N
        lblTarget1.setText("39");
        getContentPane().add(lblTarget1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, 60, 80));

        lblUnidTarget1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblUnidTarget1.setText("min");
        getContentPane().add(lblUnidTarget1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, 50, 80));

        iconTargetBkg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ControleDeBrassagem/Images/Rectangle 34.png"))); // NOI18N
        getContentPane().add(iconTargetBkg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, 120, 100));

        lblUnidTarget.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblUnidTarget.setText("ºC");
        getContentPane().add(lblUnidTarget, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, 50, 80));

        iconTargetBkg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ControleDeBrassagem/Images/Rectangle 34.png"))); // NOI18N
        getContentPane().add(iconTargetBkg, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 120, 100));

        btnBottomArrow1.setBackground(new java.awt.Color(51, 153, 255));
        btnBottomArrow1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBottomArrow1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnBottomArrow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 420, 40, 30));

        btnTopArrow1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTopArrow1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTopArrow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 370, 40, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ControleDeBrassagem/Images/Wallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        new Interface().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnBottomArrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBottomArrowActionPerformed
        // TODO add your handling code here:
        targetValue--;
        lblTarget.setText(Integer.toString(targetValue));
    }//GEN-LAST:event_btnBottomArrowActionPerformed

    private void btnTopArrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTopArrowActionPerformed
        // TODO add your handling code here:
        targetValue++;
        lblTarget.setText(Integer.toString(targetValue));
    }//GEN-LAST:event_btnTopArrowActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        status = new StatusController();
        actualRampArray = new JSONArray();
        
        switch(config){
            case 0:
                status.writeStatus("Tank1", "SetPoint", targetValue);
                lblConfig.setText("Quantidade de rampas: ");
                lblUnidTarget.setVisible(false);
                setTargetsValues(0,0);
                config++;
                break;
            case 1:
                rampsNumber =  targetValue;
                lblConfig.setText("Temperatura rampa 1:");
                lblUnidTarget.setVisible(true);
                lblConfig1.setText("tempo rampa 1:");
                setSecondConfigVisible(true);
                setTargetsValues(0,0);
                config++;
                break;
            case 2:
                actualRampArray.add(Integer.parseInt(lblTarget.getText()));
                actualRampArray.add(Integer.parseInt(lblTarget1.getText()));
                allRampsArray.add(actualRampArray);
                rampsNumber--;
                actualRamp++;
                lblConfig.setText("Temperatura rampa " + Integer.toString(actualRamp) + ":");
                lblConfig1.setText("tempo rampa "+ Integer.toString(actualRamp) + ":");
                setTargetsValues(0,0);
                if(rampsNumber ==  0){
                    status.writeStatus("Tank1", "Ramps", allRampsArray);
                    setSecondConfigVisible(false);
                    lblConfig.setText("Tempo de clarificação:");
                    lblUnidTarget.setText("min");
                    config++;
                }
                break;
            case 3:
                status.writeStatus("Tank2", "ClarificationTime", Integer.parseInt(lblTarget.getText()));
                setTargetsValues(0,0);
                lblConfig.setText("Temperatura de fervura:");
                lblUnidTarget.setText("ºC");
                config++;
                break;
            
            case 4:
                status.writeStatus("Tank3", "SetPoint", Integer.parseInt(lblTarget.getText()));
                setTargetsValues(0,0);
                lblConfig.setText("Tempo de fervura:");
                lblUnidTarget.setText("min");
                config++;
                break;
              
             case 5:
                 status.writeStatus("Tank3", "BoilTime", Integer.parseInt(lblTarget.getText()));
                 setTargetsValues(0,0);
                 lblConfig.setText("Quantidade de Lúpulos: ");
                 lblUnidTarget.setVisible(false);
                  config++;
                break;
             case 6:
                 hopsNumber = targetValue;
                 lblConfig.setText("Tempo do 1º Lúpulo:");
                 lblUnidTarget.setVisible(true);
                 setTargetsValues(0,0);
                config++;
                break;
             case 7:
                 allHopsArray.add(Integer.parseInt(lblTarget.getText()));
                 hopsNumber--;
                 actualHop++;
                 lblConfig.setText("Tempo do " + Integer.toString(actualHop) + "º  Lúpulo:");
                 setTargetsValues(0,0);
                 if(hopsNumber == 1){
                     lblNext.setText("FINALIZAR");
                 }
                 if(hopsNumber == 0){
                     status.writeStatus("Tank3", "Hops", allHopsArray);
                     new Interface().setVisible(true);
                    dispose();
                 }
                break;
             case 8:
                break;
        }
        
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnBottomArrow1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBottomArrow1ActionPerformed
        // TODO add your handling code here:
        target1Value--;
        lblTarget1.setText(Integer.toString(target1Value));
    }//GEN-LAST:event_btnBottomArrow1ActionPerformed

    private void btnTopArrow1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTopArrow1ActionPerformed
        // TODO add your handling code here:
        target1Value++;
        lblTarget1.setText(Integer.toString(target1Value));
    }//GEN-LAST:event_btnTopArrow1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaNovaBrassagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaNovaBrassagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaNovaBrassagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaNovaBrassagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaNovaBrassagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBottomArrow;
    private javax.swing.JButton btnBottomArrow1;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnTopArrow;
    private javax.swing.JButton btnTopArrow1;
    private javax.swing.JLabel iconBottomArrow;
    private javax.swing.JLabel iconBottomArrow1;
    private javax.swing.JLabel iconTargetBkg;
    private javax.swing.JLabel iconTargetBkg1;
    private javax.swing.JLabel iconTopArrow;
    private javax.swing.JLabel iconTopArrow1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblConfig;
    private javax.swing.JLabel lblConfig1;
    private javax.swing.JLabel lblNext;
    private javax.swing.JLabel lblTarget;
    private javax.swing.JLabel lblTarget1;
    private javax.swing.JLabel lblUnidTarget;
    private javax.swing.JLabel lblUnidTarget1;
    // End of variables declaration//GEN-END:variables


private void setSecondConfigVisible(boolean value){
    lblTarget1.setVisible(value);
    lblConfig1.setVisible(value);
    btnBottomArrow1.setVisible(value);
    btnTopArrow1.setVisible(value);
    iconBottomArrow1.setVisible(value);
    iconTopArrow1.setVisible(value);
    iconTargetBkg1.setVisible(value);
    lblUnidTarget1.setVisible(value);
}

private void setTargetsValues(int t1, int t2){
    targetValue  = t1;
    lblTarget.setText(Integer.toString(t1));
    target1Value  = t2;
    lblTarget1.setText(Integer.toString(t2));
}


}
